In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.model_selection import cross_val_score
import seaborn as sns
# For manupulating the data
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
# Models under the Sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans
# to calculate the performances of the models 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score # score evaluation
from sklearn.model_selection import cross_val_predict # prediction
from keras.models import Sequential
from keras.layers import Dense
from sklearn.neural_network import MLPClassifier
from sklearn import preprocessing
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RepeatedStratifiedKFold

**Dataset**

This dataset contains occurrences of hepatitis in people. 
The dataset has been downloaded from  “hepatitis_csv dataset.” https://www.openml.org/d/55, and the code was programmed in Google Colab. 

**2. Data Preparation: Dropping the rows with NaN**

In [ ]:
data = pd.read_csv("/content/hepatitis_csv.csv")
#data.head(20)

In [ ]:
# a list with all missing value formats
missing_value_formats = ["n.a.","?","NA","n/a", "na", "--", "NaN"]
df = pd.read_csv("/content/hepatitis_csv.csv", na_values = missing_value_formats)

#print steroid again
#print(df.head(30))
#df

In [ ]:
print(data.isnull().sum())

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64


In [ ]:
# Drops all rows with NaN values
data.dropna(axis=0,inplace=True)
#data.shape

In [ ]:
df = data.copy()
# Data has ordinal attributes, The LabelEncoder has been used to make into numerical values  
Lb = LabelEncoder()
# iterating the encoding all the attributes
for features in df.columns:
    df[features] = Lb.fit_transform(df[features])
#df.head(100)

In [ ]:
Y = df['class']
X = df.loc[:,:'histology']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

2.1. Gradient Boosting Classifier

In [ ]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
clf = GradientBoostingClassifier(n_estimators=1000,max_depth=3,learning_rate=0.05)
print("Accuracy --> "+str(np.mean(cross_val_score(clf,X,Y,cv=cv))))


Accuracy --> 0.8333333333333334


In [ ]:
clf.fit(X_train, y_train)
# Prediction and Confusion Matrix
y_pred = clf.predict(X_test)
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 2  1]
 [ 3 10]]
              precision    recall  f1-score   support

           0       0.40      0.67      0.50         3
           1       0.91      0.77      0.83        13

    accuracy                           0.75        16
   macro avg       0.65      0.72      0.67        16
weighted avg       0.81      0.75      0.77        16



In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.25
Mean Squared Error: 0.25
Root Mean Squared Error: 0.5


2.2. Random Forest Classifie

In [ ]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
clf = RandomForestClassifier(n_estimators=1000,random_state=0) # Best performance at current parameters
print("Accuracy --> "+str(np.mean(cross_val_score(clf,X,Y,cv=cv))))
#print("Recall --> "+str(np.mean(cross_val_score(clf,X,Y,cv=5,scoring='recall'))))

Accuracy --> 0.8958333333333334


In [ ]:
clf.fit(X_train, y_train)
# Prediction and Confusion Matrix
y_pred = clf.predict(X_test)
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 2  1]
 [ 1 12]]
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.92      0.92      0.92        13

    accuracy                           0.88        16
   macro avg       0.79      0.79      0.79        16
weighted avg       0.88      0.88      0.88        16



In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.125
Mean Squared Error: 0.125
Root Mean Squared Error: 0.3535533905932738


2.3. Decision Tree Classifier

In [ ]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
clf = tree.DecisionTreeClassifier() # Best performance at current parameters
print("Accuracy --> "+str(np.mean(cross_val_score(clf,X,Y,cv=cv))))
# print("Recall --> "+str(np.mean(cross_val_score(clf,X,y,cv=5,scoring='recall'))))

Accuracy --> 0.8375


In [ ]:
clf.fit(X_train, y_train)
# Prediction and Confusion Matrix
y_pred = clf.predict(X_test)
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[2 1]
 [4 9]]
              precision    recall  f1-score   support

           0       0.33      0.67      0.44         3
           1       0.90      0.69      0.78        13

    accuracy                           0.69        16
   macro avg       0.62      0.68      0.61        16
weighted avg       0.79      0.69      0.72        16



In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.3125
Mean Squared Error: 0.3125
Root Mean Squared Error: 0.5590169943749475


2.4. K Neighbors Classifier

In [ ]:
max_i = -1
score = -1
max_i_ = -1
score_ = -1
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
for i in range(1,20):
    
    clf = KNeighborsClassifier(n_neighbors=i)
    temp = np.mean(cross_val_score(clf,X,Y,cv=cv))
    # temp2 = np.mean(cross_val_score(clf,X,Y,cv=5,scoring='recall'))
    # if temp2>score_:
    #     score_=temp2
    #     max_i_=i
    # if temp>score:
    #     score = temp
    #     max_i = i
    print("At k="+str(i)+" accuracy-->"+str(temp))
    # print("At k="+str(i)+" recall-->"+str(temp2))
print("***************************************************")
print("Maximum accuracy-->"+str(score)+" at k="+str(max_i))
print("Maximum recall-->"+str(score_)+" at k="+str(max_i_))

At k=1 accuracy-->0.825
At k=2 accuracy-->0.8375
At k=3 accuracy-->0.8416666666666667
At k=4 accuracy-->0.8583333333333333
At k=5 accuracy-->0.85
At k=6 accuracy-->0.8291666666666667
At k=7 accuracy-->0.8583333333333333
At k=8 accuracy-->0.8416666666666667
At k=9 accuracy-->0.8416666666666667
At k=10 accuracy-->0.8416666666666667
At k=11 accuracy-->0.8333333333333334
At k=12 accuracy-->0.8208333333333333
At k=13 accuracy-->0.8208333333333333
At k=14 accuracy-->0.8125
At k=15 accuracy-->0.8333333333333334
At k=16 accuracy-->0.8291666666666667
At k=17 accuracy-->0.8375
At k=18 accuracy-->0.8416666666666667
At k=19 accuracy-->0.8375
***************************************************
Maximum accuracy-->-1 at k=-1
Maximum recall-->-1 at k=-1


In [ ]:
clf.fit(X_train, y_train)
# Prediction and Confusion Matrix
y_pred = clf.predict(X_test)
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 0  3]
 [ 0 13]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.81      1.00      0.90        13

    accuracy                           0.81        16
   macro avg       0.41      0.50      0.45        16
weighted avg       0.66      0.81      0.73        16



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.1875
Mean Squared Error: 0.1875
Root Mean Squared Error: 0.4330127018922193


2.5. SVM

In [ ]:
# training a SVM classifier
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
#clf = SVC(kernel = 'linear', C = 1, random_state = 0)  
#clf = SVC(kernel = 'poly', C = 1, random_state = 0)  
clf = SVC(kernel = 'rbf', C = 10, random_state = 0)
print("Accuracy --> "+str(np.mean(cross_val_score(clf,X,Y,cv=cv))))  

Accuracy --> 0.875


In [ ]:
clf.fit(X_train, y_train)
# Prediction and Confusion Matrix
y_pred = clf.predict(X_test)
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 2  1]
 [ 0 13]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       0.93      1.00      0.96        13

    accuracy                           0.94        16
   macro avg       0.96      0.83      0.88        16
weighted avg       0.94      0.94      0.93        16



In [ ]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.0625
Mean Squared Error: 0.0625
Root Mean Squared Error: 0.25


2.6. MLP Classifier

In [ ]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
X_scale = min_max_scaler.fit_transform(X)
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.2)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.2)

In [ ]:
model = Sequential([
    Dense(32, activation='relu', input_shape=(19,)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid'),
])
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])
hist = model.fit(X_train, y_train,
          batch_size=32, epochs=100,
          validation_data=(X_val, Y_val))

Epoch 1/100
2/2 [==============================] - 1s 245ms/step - loss: 0.7437 - accuracy: 0.3125 - val_loss: 0.7703 - val_accuracy: 0.2500
Epoch 2/100
2/2 [==============================] - 0s 46ms/step - loss: 0.7085 - accuracy: 0.4167 - val_loss: 0.7399 - val_accuracy: 0.4167
Epoch 3/100
2/2 [==============================] - 0s 54ms/step - loss: 0.6573 - accuracy: 0.5208 - val_loss: 0.7136 - val_accuracy: 0.4167
Epoch 4/100
2/2 [==============================] - 0s 51ms/step - loss: 0.6518 - accuracy: 0.5521 - val_loss: 0.6904 - val_accuracy: 0.5833
Epoch 5/100
2/2 [==============================] - 0s 48ms/step - loss: 0.6240 - accuracy: 0.6875 - val_loss: 0.6698 - val_accuracy: 0.6667
Epoch 6/100
2/2 [==============================] - 0s 53ms/step - loss: 0.5964 - accuracy: 0.7708 - val_loss: 0.6518 - val_accuracy: 0.7500
Epoch 7/100
2/2 [==============================] - 0s 50ms/step - loss: 0.5831 - accuracy: 0.7812 - val_loss: 0.6359 - val_accuracy: 0.8333
Epoch 8/100
2/2 [==